version: '3.3'

services:
   db:
     image: mysql:5.6
     ports:
      - "4306:3306"
     volumes:
       - db_data:/var/lib/mysql
       - ./sql/init.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
     restart: always
     env_file: .env

volumes:
    db_data: {}
