# Generated by Django 3.0.6 on 2020-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0002_prediction_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unixtime', models.PositiveIntegerField(unique=True)),
                ('yen', models.FloatField()),
                ('btc', models.FloatField()),
                ('asset', models.FloatField()),
            ],
        ),
    ]
